### ISSUE TITLE
Use custom shaders by exposing shader handles?

### ISSUE THREAD

**Issue by zainthemaynnn** [komadori/bevy_mod_outline#15]
hey, I wanted to add an animated effect to the outlines which involved changing its thickness on a per-vertex basis.

this involved copy and pasting the `OUTLINE_SHADER_HANDLE` into `load_internal_asset!` in order to overwrite the built-in shader with a new one. which is a bit hacky.

would it be possible to make `OUTLINE_SHADER_HANDLE` and `FRAGMENT_SHADER_HANDLE` public? or is there another way I should be doing this? thanks.

**Comment by komadori** [comment]
Hi, sorry I took so long to respond to this. I wasn't sure what to think at first. However, after some consideration, I conclude that the interface between the shader and the library is an implementation detail which is subject to change at any time. Hence, the handle ID is private. Copying the handle ID into your program may work, but the fact that it feels hacky should remind you that it may break in any future release.

I think the right way to do this is to maintain a vendor fork with this feature added.
