### ISSUE TITLE
Add `AsyncSceneOutline`

### ISSUE THREAD

**Issue by Shatur** [komadori/bevy_mod_outline#30]
bevy_xpbd have [AsyncSceneCollider](https://docs.rs/bevy_xpbd_3d/0.3.3/bevy_xpbd_3d/components/struct.AsyncSceneCollider.html)  which initializes all colliders from meshes after scene loading.

It would be convenient to provide something like `AsyncSceneOutline` component and a system that listens for [SceneInstanceReady](https://docs.rs/bevy/latest/bevy/scene/struct.SceneInstanceReady.html) event and for all entities with `AsyncSceneOutline` inserts [InheritOutlineBundle](https://docs.rs/bevy_mod_outline/latest/bevy_mod_outline/struct.InheritOutlineBundle.html) to all their children.

**Comment by komadori** [comment]
Good idea, thanks. Added by 87df3aaf708e6c64b1340d137aeb481506c01bff.

**Comment by Shatur** [comment]
I suggested the marker component initially, but they decided on the event, so I edited the issue.
After using it for some time, I found it quite convenient.

**Comment by komadori** [comment]
Yes, I saw. Thanks for working on it. I think it will use some kind of per-entity event/observer pattern in the future once Bevy has support for it, and that will be the best solution.
