### ISSUE TITLE
HDR and active OutlineVolume affects DirectionalLight

### ISSUE THREAD

**Issue by jannik4** [komadori/bevy_mod_outline#37]
If a camera with hdr activated and a DirectionalLight is used in the scene, the rendering of an outline affects the light of the entire scene.
This only happens with hdr and a DirectionalLight. Non-hdr cameras and PointLights seem not to be affected.

Notice the subtle color change of the plane.

Without Outlines in the scene:
![Screenshot 2024-04-26 223037](https://github.com/komadori/bevy_mod_outline/assets/50554200/0c4022a4-62c2-430e-8ab1-028e36baf0ee)

With Outlines in the scene:
![Screenshot 2024-04-26 223024](https://github.com/komadori/bevy_mod_outline/assets/50554200/70a83214-65cf-4820-85e7-0eb82229c2cc)

**Comment by jannik4** [comment]
Example to reproduce: https://github.com/jannik4/bevy_mod_outline/blob/4934a02ac69935e22f994c90886e20b9cad872b3/examples/shapes.rs

**Comment by komadori** [comment]
I think this has the same cause as #36. Writing to the sampled colour attachment overwrites the unsampled one, and effectively disable some of the earlier post-processing steps such as tone-mapping.

**Comment by komadori** [comment]
Fixed in 0.7.1.
