### ISSUE TITLE
Scene.rs line 18 should use get_entity to avoid panic 

### ISSUE THREAD

**Issue by ethereumdegen** [komadori/bevy_mod_outline#45]
thread 'Compute Task Pool (3)' panicked at /home/andy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_mod_outline-0.8.2/src/scene.rs:18:22:
Attempting to create an EntityCommands for entity Entity { index: 1206, generation: 1 }, which doesn't exist.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_mod_outline::scene::process_async_scene_outline`!

**Comment by ethereumdegen** [comment]
this pattern is always preferred in bevy..



			commands.get_entity(scene_entity).map( |mut cmd| 

				{ 
				
				} )

**Comment by ethereumdegen** [comment]
or use try_insert

**Comment by komadori** [comment]
Fixed in 0.8.3.
